name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Android
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Build iOS
        run: |
          cd ios
          xcodebuild -workspace amplify_rn.xcworkspace -scheme amplify_rn -configuration Release

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
        run: |
          aws s3 cp android/app/build/outputs/apk/release/app-release.apk s3://letsapp.store/android/app-release.apk
          aws s3 cp ios/build/Release-iphoneos/amplify_rn.ipa s3://letsapp.store/ios/amplify_rn.ipa
